[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"

btc_lib = { path = "../lib"}
clap = { version = "4.5.26", features = ["derive"] }
flume = "0.11.1"
tokio = { version = "1.42.0", features = ["full"] }
